FROM node:lts-alpine AS deps

# Install Native Dependencies
RUN apk --no-cache add python make g++ postgresql-client

WORKDIR /opt/app

COPY package.json package.json
COPY .yarnrc.yml .yarnrc.yml
COPY .pnp.js .pnp.js
COPY yarn.lock yarn.lock 
COPY .yarn  .yarn

RUN yarn

COPY ./ ./

